steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wellness-backend:$COMMIT_SHA'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wellness-backend:latest'
  - '-f'
  - 'backend/Dockerfile'
  - '.'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wellness-backend:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wellness-backend:latest'

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'wellness-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/wellness-backend:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '2Gi'
  - '--cpu'
  - '2'
  - '--max-instances'
  - '10'
  - '--min-instances'
  - '0'
  - '--port'
  - '5000'
  - '--timeout'
  - '300'
  - '--concurrency'
  - '100'
  - '--set-env-vars'
  - 'FLASK_ENV=production'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY 